# Generated by Django 6.0.6 on 2026-06-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='display_number',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
